# PARTE DEL EXAMEN: complete el Pipeline.
name: Pipeline de CI/CD

on:
  push:
    branches:
      - main

job:
  instalacion:
    steps:
        - uses: azure/nodejs@v6
        - uses: azure/checkout@v6
        # TODO: instalar dependencias
        - name: "Instalar dependencias"
        - run: "npm install"
        # TODO: ejecutar pruebas
        - name: "Ejecutar Pruebas"
        - run: "npm test"


